# Official docu
# https://www.elastic.co/guide/en/elasticsearch/reference/7.8/docker.html
version: '2.2'
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
    container_name: es
    environment:
      - node.name=es
      - cluster.name=es-docker
      - cluster.initial_master_nodes=es
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

volumes:
  data01:
    driver: local
